#!/usr/bin/php
<?php

// Number of jobs to run in parallel
$parallelJobs = 3;

// Build array with jobs to execute
$jobs = array();

// Data sets we know of
$datasets = array(
    'arbit'   => 'data/arbit_html/*.xml',
    'dblp'    => 'data/dblp/dblp20040213_fixed.xml',
    'mhgta'   => 'data/mhgta/*.xml.fixed.fixed',
    'webfrap' => 'data/webfrap/*.bdl',
);

// Build DTD inferencing jobs from them
foreach ( $datasets as $name => $dataset )
{
    $jobs[] = './learn -t dtd ' . $dataset . ' > inferenced/' . $name . '_none_none_0.dtd';
}

// Build XSD and bonxai inferencing job commands
foreach ( array( 'xsd', 'bonxai' ) as $type )
{
    foreach ( array( '0', '1', '3', 'n' ) as $locality )
    {
        foreach ( array( 'strict', 'same', 'equals', 'merge' ) as $attr )
        {
            foreach ( array( 'exact', 'node-based', 'subsumed' ) as $ptrn )
            {
                foreach ( $datasets as $name => $dataset )
                {
                    $jobs[] = "./learn -t $type -l $locality -a $attr -p $ptrn $dataset > inferenced/${name}_${ptrn}_${attr}_${locality}.${type}";
                }
            }
        }
    }
}

// Run main loop as long as there are jobs remaining
$forks = array();
while ( ( $job = array_pop( $jobs ) ) !== null )
{
    if ( count( $forks ) < $parallelJobs )
    {
        // Start a new job
        echo "Forking child\n";
        if ( ( $forks[] = pcntl_fork() ) === 0 )
        {
            // We are the newly forked child, just execute the job
            shell_exec( $job );
            exit( 0 );
        }
    }

    do {
        // Check if the registered jobs are still alive
        foreach ( $forks as $nr => $pid )
        {
            if ( $pid === pcntl_waitpid( $pid, $status, WNOHANG ) )
            {
                echo "Child finished execution\n";
                // Job has finished
                unset( $forks[$nr] );
            }
        }

        // Sleep a bit, to not overload with the angel process
        usleep( 100 * 1000 );
    } while ( count( $forks ) >= $parallelJobs );
}

