#!/usr/bin/php
<?php
/**
 * Schema learning
 *
 * This file is part of SchemaLearner.
 *
 * SchemaLearner is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3 of the License.
 *
 * SchemaLearner is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with SchemaLearner; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @package Core
 * @version $Revision: 1236 $
 * @license http://www.gnu.org/licenses/gpl-3.0.txt GPL
 */

require __DIR__ . '/src/environment.php';

// Handle provided options
$defaults = array(
    'help' => null,
    'type' => 'dtd',
    'root' => null,
);

$mapping = array(
    'h' => 'help',
    't' => 'type',
    'r' => 'root',
);

$options = getopt(
    'ht:r:',
    array(
        'help',
        'type:',
        'root:',
    )
);

// Merge options
foreach ( $mapping as $short => $long )
{
    if ( isset( $options[$short] ) &&
         !isset( $options[$long] ) )
    {
        $options[$long] = $options[$short];
        unset( $options[$short] );
    }
}
$options += $defaults;

// Show help output, if requested
if ( ( $options['help'] !== null ) ||
     ( count( $argv ) <= 1 ) )
{
    echo <<<EOHELP
Scheam Learner
by Kore Nordmann

Usage: {$argv[0]} [-t <type>] (-r <root>)+ <xml-files>

-t / --type     Type of the schema to generate. Currently implemented schema 
                languages: dtd, xsd
-r / --root     Root element(s) used in the schema. Is not yet detected from 
                the provided XML files.

-h / --help     Display this help output

EOHELP;
    exit( 0 );
}

// Handle required arguments errors
if ( $options['root'] === null )
{
    echo "Please provide at least one root element. This caanot yet be inferenced from the XML files.\n";
    exit( 1 );
}

$files = array_slice( $argv, 1 );

$dtdSchema = new slDtdSchema();
foreach ( $files as $file )
{
    if ( !file_exists( $file ) )
    {
        continue;
    }

    $dtdSchema->learnFile( $file );
}

switch ( $options['type'] )
{
    case 'dtd':
        $visitor = new slSchemaDtdVisitor( $options['root'] );
        echo $visitor->visit( $dtdSchema );
        exit( 0 );

    case 'xsd':
        $visitor = new slSchemaXmlSchemaVisitor( is_array( $options['root'] ) ? $options['root'] : array( $options['root'] ) );
        echo $visitor->visit( $dtdSchema );
        exit( 0 );

    default:
        echo "Unknown schema type '{$options['type']}'.\n";
        exit( 2 );
}


