#!/usr/bin/env php
<?php

// List of special test modules.
$modules = array(
	'visitor' => array( 'slVisitorTests', 'tests/visitor_suite.php' ),
	'main'    => array( 'slMainTests', 'tests/main_suite.php' ),
);

$module = false;
if ( isset( $modules[end( $argv )] ) )
{
    $module = array_pop( $argv );
}

$module = false;
if ( isset( $modules[end( $argv )] ) )
{
    $module = array_pop( $argv );
}

$argv = array_merge(
    array( 'phpunit' ),
    array_slice( $argv, 1 ),
    array( '--configuration', 'tests/phpunit.xml' )
);

// Check if the test should only be run for a specified module.
if ( $module )
{
    $_SERVER['argv'] = array_merge( $argv, $modules[$module] );
}
else
{
    $_SERVER['argv'] = array_merge( $argv, array( 'arbitTestSuite', 'tests/suite.php' ) );
}

echo "Executing: ", array_reduce( array_map( function( $arg ) { return escapeshellarg( $arg ); }, $_SERVER['argv'] ), function( $a, $b ) { return $a . ' ' . $b; } ), "\n";

require_once 'PHPUnit/Autoload.php';

require __DIR__ . '/tests/runner/command.php';
arbitTextUiCommand::main();

